### ISSUE TITLE
subinacl command fails

### ISSUE THREAD

**Issue by DrissiReda** [Jackpison/IDM-reset#1]
The command you're using for subinacl is wrong. I'm not a windows fan so I can't help you much with it

```
C:\WINDOWS\system32>"subinacl.exe" /keyreg "HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{5ED60779-4DE2-4E07-B862-974CA4FF2E9C}" /grant="Tout le monde"=f  1>nul

Elapsed Time: 00 00:00:00
Done:        0, Modified        0, Failed        0, Syntax errors        1
Last Syntax Error:WARNING : /grant=tout le monde=f : Error when checking arguments - HKEY_CURRENT_USER\Software\Classes\Wow6432Node\CLSID\{5ED60779-4DE2-4E07-B862-974CA4FF2E9C}
```

**Comment by askfriends** [comment]
link to subinacl tool in readme is broken, MS says this tool is not available anymore..

**Comment by novasapper5431** [comment]
> link to subinacl tool in readme is broken, MS says this tool is not available anymore..

Found an archive on archive.org:
https://web.archive.org/web/20190910062448/http://download.microsoft.com/download/1/7/d/17d82b72-bc6a-4dc8-bfaa-98b37b22b367/subinacl.msi

Edit: There is an included SubInAcl.msi in the release, use that to install SubInAcl.exe to C:\Program Files (x86)\Windows Resource Kits\Tools, then copy the exe file to your IDM Reset directory.

**Comment by askfriends** [comment]
> > link to subinacl tool in readme is broken, MS says this tool is not available anymore..
> 
> Found an archive on archive.org:
> https://web.archive.org/web/20190910062448/http://download.microsoft.com/download/1/7/d/17d82b72-bc6a-4dc8-bfaa-98b37b22b367/subinacl.msi
> 
> Edit: There is an included SubInAcl.msi in the release, use that to install SubInAcl.exe to C:\Program Files (x86)\Windows Resource Kits\Tools, then copy the exe file to your IDM Reset directory.

thanks for the update.
so do you confirm this script is still working?

**Comment by shadow443** [comment]
I have the same problem with subinacl. Try another method here https://github.com/J2TEAM/idm-trial-reset/issues/10#issuecomment-616135590 they say you have to rename this {07999AC3-058B-40BF-984F-69EB1E554CA7} but I can't just get " access denied"

**Comment by Jackpison** [comment]
Keep subinacl.msi & resetrialidm.bat in the same folder, and run the .bat file as an administrator only.
